# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-04 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20200521_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackerapplication',
            name='under_age',
        ),
        migrations.RemoveField(
            model_name='mentorapplication',
            name='under_age',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='under_age',
        ),
        migrations.AddField(
            model_name='hackerapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], default=2018),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], default=2018),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Oxford Hack 2020 2016'), (1, 'Oxford Hack 2020 2017'), (2, 'Oxford Hack 2020 2018'), (3, 'Oxford Hack 2020 2019')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], default=2018),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Oxford Hack 2020 2016'), (1, 'Oxford Hack 2020 2017'), (2, 'Oxford Hack 2020 2018'), (3, 'Oxford Hack 2020 2019')], max_length=7, null=True),
        ),
    ]
